ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

shop/urls.py
from django.urls import path, include
from shop import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

router = DefaultRouter()
router.register(r'cart_item', views.CartItemAViewSet, basename='cart_item')
router.register(r'delivery_address', views.DeliveryAddressModelViewSet, basename='delivery_address')
router.register(r'order_detail', views.OrderDetail, basename='order_detail')


urlpatterns = [
    path('users/', views.UserListDetailView.as_view(), name="users"),
    path('user/<int:user_id>/store/', views.StoreListView.as_view(), name="store"),
    path('user/<int:user_id>/store/<int:store_id>/product/', views.ProductListView.as_view(), name="products"),
    path('product/<int:product_id>/', views.ProductDetailView.as_view(), name="product"),
    path('user/<int:user_id>/cart/', views.CartAPIView.as_view(), name="cart"),
    # path('user/<int:user_id>/cart/<int:cart_id>/cart_item/', views.CartItemAPIView.as_view(), name="cart_item"),
    path('api/', include(router.urls)),
    path('order/', views.OrderList.as_view(), name='order_list'),

    path('api_token_auth/', obtain_auth_token, name='obtain_auth_token'),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))
]

shop/models.py
from datetime import datetime
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from guardian.shortcuts import assign_perm


class MyUser(AbstractUser):
    TYPE_CHOICE = (
        ('S', 'Seller'),
        ('C', 'Customer')
    )
    user_type = models.CharField(max_length=2, choices=TYPE_CHOICE, default='S')
    is_customer = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ("can_message", "Can send message"),
        )

    def __str__(self):
        return self.username


class Store(models.Model):
    seller_user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='store_seller_user')

    def __str__(self):
        return self.seller_user.username


class Product(models.Model):
    CATEGORY_CHOICE = (
        ('CLT', 'clothes'),
        ('SH', 'shoes'),
        ('MOB', 'mobiles'),
        ('LAP', 'laptops'),
        ('WTC', 'watches'),
    )
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name='product_store', null=True)
    category = models.CharField(max_length=3, choices=CATEGORY_CHOICE, default=None)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to="product_image", blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField(null=True)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    customer_user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart_customer_user')
    created_at = models.DateTimeField(default=datetime.now)

    class Meta:
        permissions = (
            ("can_checkout", "Can checkout"),
        )

    def __int__(self):
        return self.id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    # def save(self, *args, **kwargs):
    #     user = kwargs['request'].user
    #     super(CartItem, self).save(*args)
    #     assign_perm('view_cartitem', user, self)
    #     assign_perm('delete_cartitem', user, self)
    #     return self


class DeliveryAddress(models.Model):
    customer_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='delivery_customer_user')
    full_name = models.CharField(max_length=250, null=True)
    number = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=250, null=True)
    email = models.EmailField(null=True)
    postal_code = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.address


class Order(models.Model):
    customer_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='order_customer_user')
    product = models.ManyToManyField(Product, related_name='order_product', blank=True)
    quantity = models.IntegerField(default=0)
    delivery_address = models.ForeignKey(DeliveryAddress, on_delete=models.CASCADE, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True)

    # def save(self, *args, **kwargs):
    #     user = kwargs['request'].user
    #     super(Order, self).save(*args)
    #     assign_perm('view_order', user, self)
    #     assign_perm('delete_order', user, self)
    #     return self

    def __int__(self):
        return self.id

shop/views.py
from django.db import IntegrityError
from django.http import Http404
from django.shortcuts import get_object_or_404
from rest_framework import status, viewsets, mixins, generics
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.settings import api_settings
from rest_framework.views import APIView
from shop.models import Product, MyUser, Store, Cart, CartItem, DeliveryAddress, Order
from shop.serializers import ProductSerializer, MyUserSerializer, StoreSerializer, \
    CreateStoreSerializer, ProductUpdateSerializer, CartListSerializer, CartDetailSerializer, \
    CartItemDetailSerializer, DeliveryAddressSerializer, OrderSerializer, OrderUpdateSerializer
from shop.services import CreateStoreViewService, CreateCartItemViewService
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated, IsAdminUser


class UserListDetailView(APIView):
    """
    List one and all users.
    """

    def get(self, request, pk=None) -> Response:
        if pk:
            user = MyUser.objects.get(pk=pk)
            serializer = MyUserSerializer(user)
        else:
            users = MyUser.objects.all()
            serializer = MyUserSerializer(users, many=True)

        return Response(serializer.data)

    # def post(self, request):
    #     serializer = MyUserCreateSerializer(data=request.data)
    #     import pdb;pdb.set_trace()
    #     if serializer.is_valid(raise_exception=True):
    #         serializer.save()


class StoreListView(APIView):
    """
    List of all stores, or create a new store.
    """

    @classmethod
    def get(cls, request, user_id, pk=None) -> Response:
        try:
            # import pdb;pdb.set_trace()
            store = Store.objects.filter(seller_user_id=user_id)
            serializer = StoreSerializer(store, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)

        except Store.DoesNotExist:
            return Response({"Error": "Invalid store id {} not exist.".format(pk)})

    @classmethod
    def post(cls, request, user_id) -> Response:
        serializer = CreateStoreSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serial_data = serializer.validated_data
            store = CreateStoreViewService.execute(serial_data)
            if type(store) == int:
                return Response(store.id, status=status.HTTP_201_CREATED)
            return Response(store, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductListView(APIView):
    """
    List all products, or create a new product.
    """
    pagination_class = api_settings.DEFAULT_PAGINATION_CLASS
    paginator = pagination_class()
    # authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated,]

    @classmethod
    def get(cls, request, user_id, store_id) -> Response:
        import pdb;pdb.set_trace()
        product_list = Product.objects.filter(store_id=store_id)
        products = cls.paginator.paginate_queryset(product_list, request)
        serializer = ProductSerializer(products, many=True)
        return cls.paginator.get_paginated_response(serializer.data)
        # return Response(serializer.data, status=status.HTTP_200_OK)

    @classmethod
    def post(cls, request, user_id, store_id) -> Response:
        try:
            serializer = ProductSerializer(data=request.data)
            if serializer.is_valid(raise_exception=True):
                product = serializer.save()
                return Response({"Product_id": product.id}, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        except IntegrityError:
            return Response({"Error": "Invalid store id {} not exist.".format(int(request.data["store_id"]))})

        except Exception:
            return Response({"Error": "This ({}) Category does not exist".format(request.data["category"])})


class ProductDetailView(APIView):
    """
    Retrieve, update or delete a product instance.
    """

    @classmethod
    def get_object(cls, pk) -> Product:
        try:
            return Product.objects.get(pk=pk)
        except Product.DoesNotExist:
            raise Http404

    @classmethod
    def get(cls, request, user_id, store_id, product_id) -> Response:
        product = cls.get_object(product_id)
        serializer = ProductSerializer(product)
        return Response(serializer.data, status=status.HTTP_200_OK)

    @classmethod
    def patch(cls, request, product_id) -> Response:
        try:
            product = cls.get_object(product_id)
            serializer = ProductUpdateSerializer(product, data=request.data)
            if serializer.is_valid(raise_exception=True):
                serializer.save()
                import pdb;pdb.set_trace()
                return Response(serializer.data, status.HTTP_200_OK)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        except Store.DoesNotExist:
            return Response({"Error": "Invalid store id {} not exist.".format(int(request.data["store_id"]))})

    @classmethod
    def delete(cls, request, user_id, store_id, product_id) -> Response:
        product = cls.get_object(product_id)
        product.delete()
        return Response({"Delete: Product successfully deleted."}, status=status.HTTP_204_NO_CONTENT)


class CartAPIView(APIView):
    """
    Create, retrieve, update or delete a cart instance.
    """

    def get(self, request, user_id, pk=None):
        try:
            if pk:
                cart = Cart.objects.get(pk=pk)
                serializer = CartListSerializer(cart)
            else:
                carts = Cart.objects.all()
                serializer = CartListSerializer(carts, many=True)
            return Response(serializer.data, status.HTTP_200_OK)
        except Cart.DoesNotExist:
            return Response({"Error": "Cart for this id-{} doest not exist.".format(pk)}, status.HTTP_404_NOT_FOUND)

    def post(self, request, user_id, ):
        # data = {"data":request.data, "customer_user":request.user}
        serializer = CartDetailSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()

    def delete(self, request, user_id, pk):
        try:
            cart = Cart.objects.get(pk=pk)
            cart.delete()
            return Response({"success": "deleted cart successfully."}, status.HTTP_204_NO_CONTENT)
        except Cart.DoesNotExist:
            return Response({"Error": "Cart for this id-{} doest not exist.".format(pk)}, status.HTTP_404_NOT_FOUND)


class CartItemAViewSet(viewsets.ViewSet):
    """
    A simple ViewSet for listing, retrieving, deleting or creating Cart items.
    """
    pagination_class = api_settings.DEFAULT_PAGINATION_CLASS
    paginator = pagination_class()

    def list(self, request):
        queryset = CartItem.objects.all()
        cart_items = self.paginator.paginate_queryset(queryset, request)
        serializer = CartItemDetailSerializer(cart_items, many=True)
        return self.paginator.get_paginated_response(serializer.data)
        # return Response(serializer.data)

    def retrieve(self, request, pk=None):
        try:
            cart_item = get_object_or_404(CartItem, pk=pk)
            serializer = CartItemDetailSerializer(cart_item)
            return Response(serializer.data)
        except Cart.DoesNotExist:
            return Response({"Error": "Cart for this id-{} doest not exist.".format(pk)}, status.HTTP_404_NOT_FOUND)

    def create(self, request):
        serializer = CartItemDetailSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            cart_item = CreateCartItemViewService.execute(serializer.data)
            return Response({"cart_item_id": cart_item.id})
        else:
            return Response(serializer.errors)

    def destroy(self, request, pk=None):
        try:
            cart_item = get_object_or_404(CartItem, pk=pk)
            cart_item.delete()
            return Response({"success": "deleted cart item successfully."}, status.HTTP_204_NO_CONTENT)
        except Cart.DoesNotExist:
            return Response({"Error": "Cart item for this id-{} doest not exist.".format(pk)},
                            status.HTTP_404_NOT_FOUND)


class DeliveryAddressModelViewSet(viewsets.ModelViewSet):
    """
    A simple ModelViewSet for viewing, editing, deleting or updating delivery address.
    """
    queryset = DeliveryAddress.objects.all()
    serializer_class = DeliveryAddressSerializer


class OrderList(mixins.ListModelMixin,
                mixins.CreateModelMixin,
                generics.GenericAPIView):
    """
    A simple GenericAPIView using mixin to fetch orders.
    """
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class OrderDetail(viewsets.ModelViewSet):
    """
     A viewset that provides the standard actions.
    """
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    @action(detail=True, methods=['get'])
    def fetch_order(self, request, pk):
        order = self.get_object()
        serializer = OrderSerializer(order)
        return Response(serializer.data)

    @action(detail=False, methods=['post'])
    def create_order(self, request):
        serializer = OrderSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data, status.HTTP_201_CREATED)
        return Response(serializer.errors)

    @action(detail=True, methods=["patch"])
    def update_order(self, request, pk):

shop/templates/address1.html
<!DOCTYPE html>
<html>
<head>
	<title>Delivery address</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">BigDaddyShop</h1>

            </div>
            <h3>Delivery address</h3>
            <p>Fill address</p>
            <form class="m-t" role="form" action="login.html">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Address" required="">
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Postal-code" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="City" required="">
                </div>
             
                <button type="submit" class="btn btn-primary block full-width m-b">Submit</button>

                <p class="text-muted text-center"><small>Already address registered?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="my_address.html"    >My address</a>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/checkout.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial;
  font-size: 17px;
  padding: 8px;
}

* {
  box-sizing: border-box;
}

.row {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
  margin: 0 -16px;
}

.col-25 {
  -ms-flex: 25%; /* IE10 */
  flex: 25%;
}

.col-50 {
  -ms-flex: 50%; /* IE10 */
  flex: 50%;
}

.col-75 {
  -ms-flex: 75%; /* IE10 */
  flex: 75%;
}

.col-25,
.col-50,
.col-75 {
  padding: 0 16px;
}

.container {
  background-color: #f2f2f2;
  padding: 5px 20px 15px 20px;
  border: 1px solid lightgrey;
  border-radius: 3px;
}

input[type=text] {
  width: 100%;
  margin-bottom: 20px;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

label {
  margin-bottom: 10px;
  display: block;
}

.icon-container {
  margin-bottom: 20px;
  padding: 7px 0;
  font-size: 24px;
}

.btn {
  background-color: #4CAF50;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 100%;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.btn:hover {
  background-color: #45a049;
}

a {
  color: #2196F3;
}

hr {
  border: 1px solid lightgrey;
}

span.price {
  float: right;
  color: grey;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the "cart" column go on top) */
@media (max-width: 800px) {
  .row {
    flex-direction: column-reverse;
  }
  .col-25 {
    margin-bottom: 20px;
  }
}
</style>
</head>
<body>

<h1>Checkout</h1>
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="", method="POST">
      {% csrf_token %}
       {{form.as_p}}
        <input type="submit" value="Continue to checkout" class="btn">

      </form>
    </div>
  </div>
  <div class="col-25">
    <div class="container">
      <h4>Cart <span class="price" style="color:black"><i class="fa fa-shopping-cart"></i> <b>{{cart_product.count}}</b></span></h4>
      {%for product in cart_product %}
      <p><a href="#">{{product.product.name}}</a> <span class="price">{{product.product.price}}</span></p>
      {%endfor%}
      <p>Total <span class="price" style="color:black"><b>{{cart_products_price}}</b></span></p>
    </div>
  </div>
</div>

</body>
</html>

shop/templates/contact1.html
<!DOCTYPE html>
<html>
<head>
	<title>Contact BDS</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body> 
        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-9">
                    
                    <ol class="breadcrumb">
                        <li>
                            <a href="index.html">Contacts</a>
                        </li>

                    </ol>
                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-4">
                <div class="contact-box">
                    <a href="profile.html">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <img alt="image" class="img-circle m-t-xs img-responsive" src="img/a2.jpg">
                            <div class="m-t-xs font-bold">Graphics designer</div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong>Vivek Thakur</strong></h3>
                        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                        <address>
                            <strong>Twitter, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890
                        </address>
                    </div>
                    <div class="clearfix"></div>
                        </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-box">
                    <a href="profile.html">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <img alt="image" class="img-circle m-t-xs img-responsive" src="img/a1.jpg">
                            <div class="m-t-xs font-bold">CEO</div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong>Rohit Bhati</strong></h3>
                        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                        <address>
                            <strong>Twitter, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890
                        </address>
                    </div>
                    <div class="clearfix"></div>
                        </a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-box">
                    <a href="profile.html">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <img alt="image" class="img-circle m-t-xs img-responsive" src="img/a3.jpg">
                            <div class="m-t-xs font-bold">Marketing manager</div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong>Shubendhu</strong></h3>
                        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                        <address>
                            <strong>Twitter, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890
                        </address>
                    </div>
                    <div class="clearfix"></div>
                        </a>
                </div>
            </div>
        </div>
        </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/product_add.html
{% extends 'index.html' %}
<!DOCTYPE html>
{%load staticfiles%}
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | E-commerce</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="css/plugins/summernote/summernote.css" rel="stylesheet">
    <link href="css/plugins/summernote/summernote-bs3.css" rel="stylesheet">

    <link href="css/plugins/datapicker/datepicker3.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">



</head>

<body>
{%block product_add%}
<div id="wrapper">

        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>Product edit</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a>E-commerce</a>
                    </li>
                    <li class="active">
                        <strong>Product edit</strong>
                    </li>
                </ol>
            </div>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight ecommerce">

            <div class="row">
                <div class="col-lg-12">
                    <div class="tabs-container">

                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#tab-1"> Product info</a></li>
                            </ul>
                            <div class="tab-content">
                                <form method="post" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div id="tab-1" class="tab-pane active">
                                    <div class="panel-body">

                                        <fieldset class="form-horizontal">

                                            <div class="form-group"><label class="col-sm-2 control-label">Name:</label>
                                                <div class="col-sm-10"><input type="text" id="id_name" name="name" class="form-control" placeholder="product name" required=""></div>
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">Price:</label>
                                                <div class="col-sm-10"><input type="text" id="id_price" name="price" class="form-control" placeholder="price" required=""></div>
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">Description:</label>
                                                <div class="col-sm-10">
                                                    <div class="summernote">
                                                        <input type="text" id="id_description" name="description" class="form-control" placeholder="description" required="">

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">Stock:</label>
                                                <div class="col-sm-10"><input type="text" id="id_stock" name="stock" class="form-control" placeholder="stock" required=""></div>
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">{{form.image.label}}:</label>
                                                {{form.image}}
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">{{form.category.label}}:</label>
                                                {{form.category}}
                                            </div>
                                            <div class="form-group">
                                                {{form.store}}
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">{{form.available.label}}:</label>
                                                {{form.available}}
                                            </div>
                                        </fieldset>

                                    </div>
                                </div>
                                    <input type="submit" value="Add product">
                                </form>


                            </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2014-2017
            </div>
        </div>

    </div>
</div>



<!-- Mainly scripts -->
<script src="js/jquery-2.1.1.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="js/inspinia.js"></script>
<script src="js/plugins/pace/pace.min.js"></script>

<!-- SUMMERNOTE -->
<script src="js/plugins/summernote/summernote.min.js"></script>

<!-- Data picker -->
<script src="js/plugins/datapicker/bootstrap-datepicker.js"></script>

<script>
    $(document).ready(function(){

        $('.summernote').summernote();

        $('.input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });

    });
</script>




{% endblock%}
</body>

</html>